GET http://localhost:3000/aboutuser

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "Jim"
}

###
GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNzM1Mzk4MDYxfQ.N7qLmy785usJ1gMOlRa5BgnNX_HQXOjj09z5jjfTs2g